apiVersion: v1
kind: Service
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-static
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-api
  selector:
    app: django-api

