apiVersion: v1
kind: Service
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: django-api

