from __future__ import annotations

from typing import Generic, Iterator, TypeVar
import datetime

T = TypeVar("T", bound=object)


class Interval(Generic[T]):
    # Construction
    def __init__(self) -> None: ...

    # Boolean / comparison
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

    # Set-like operations
    def __or__(self, other: Interval[T]) -> Interval[T]: ...
    def __and__(self, other: Interval[T]) -> Interval[T]: ...
    def __sub__(self, other: Interval[T]) -> Interval[T]: ...

    # Membership
    def __contains__(self, value: T) -> bool: ...

    # Iteration over atomic intervals
    def __iter__(self) -> Iterator[Interval[T]]: ...

    # Properties commonly used in portion
    @property
    def empty(self) -> bool: ...

    @property
    def atomic(self) -> bool: ...

    @property
    def lower(self) -> T: ...

    @property
    def upper(self) -> T: ...


def empty() -> Interval[datetime.datetime]: ...


def closedopen(lower: T, upper: T) -> Interval[T]: ...
