# Generated by Django 5.2 on 2025-08-20 23:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This is confirmed a no-op migration SQL-wise, presumably just the result of moving some help_text into models
    """

    dependencies = [
        ("fk", "0015_make_org_members_optional_20210828_2037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asrun",
            name="in_ms",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="The inpoint where the video/stream was started at. In milliseconds. Normally 0 which it defaults to.",
            ),
        ),
        migrations.AlterField(
            model_name="asrun",
            name="out_ms",
            field=models.IntegerField(
                blank=True,
                help_text="The outpoint where the video/stream stopped. This would often be the duration of the video, or how long we live streamed a particular URL. Can be null (None) if this is 'currently happening'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asrun",
            name="played_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Time when the playout started. Defaults to now.",
            ),
        ),
        migrations.AlterField(
            model_name="asrun",
            name="playout",
            field=models.CharField(
                blank=True,
                default="main",
                help_text="The playout this entry corresponds with. This will almost always be 'main' which it defaults to.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="asrun",
            name="program_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A free form text input saying what was played. If `video` is set, this field should not be set. Examples of where you'd use this field is e.g. when broadcasting live. Defaults to the empty string.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="asrun",
            name="video",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the Video which was played if there is one. Can be empty if something other than a video was played. The field is mutually exclusive with `programName`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fk.video",
            ),
        ),
        migrations.AlterField(
            model_name="fileformat",
            name="fsname",
            field=models.CharField(
                choices=[
                    ("large_thumb", "large_thumb"),
                    ("broadcast", "broadcast"),
                    ("vc1", "vc1"),
                    ("med_thumb", "med_thumb"),
                    ("small_thumb", "small_thumb"),
                    ("original", "original"),
                    ("theora", "theora"),
                    ("srt", "srt"),
                    ("cloudflare_id", "cloudflare_id"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="proper_import",
            field=models.BooleanField(
                default=False, help_text="Has the video been properly imported?"
            ),
        ),
    ]
