# Generated by Django 5.2 on 2026-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0016_alter_asrun_in_ms_alter_asrun_out_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileformat',
            name='fsname',
            field=models.CharField(choices=[('large_thumb', 'large_thumb'), ('broadcast', 'broadcast'), ('vc1', 'vc1'), ('med_thumb', 'med_thumb'), ('small_thumb', 'small_thumb'), ('original', 'original'), ('theora', 'theora'), ('srt', 'srt'), ('cloudflare_id', 'cloudflare_id')], max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='videofile',
            constraint=models.UniqueConstraint(fields=('video', 'format'), name='unique_format_per_video'),
        ),
    ]
