# Generated by Django 5.2 on 2026-08-05 23:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0017_videofile_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AlterField(
            model_name='weeklyslot',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(0))), name='scheduleitem_duration_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(0))), name='video_duration_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='weeklyslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(0))), name='weeklyslot_duration_not_negative'),
        ),
    ]
