# Generated by Django 5.2 on 2026-08-06 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0018_duration_not_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="weekly_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fk.weeklyslot",
            ),
        ),
    ]
