# Generated by Django 5.2 on 2026-08-12 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0021_video_organization_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"get_latest_by": "created_time", "ordering": ("-id",)},
        ),
    ]
