# Generated by Django 5.2.17 on 2026-08-18 01:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0022_alter_video_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="video",
        ),
        migrations.AlterModelOptions(
            name="ingestjob",
            options={"verbose_name": "ingest job"},
        ),
        migrations.RemoveField(
            model_name="ingestjob",
            name="id",
        ),
        migrations.RemoveField(
            model_name="ingestjob",
            name="job_type",
        ),
        migrations.AddField(
            model_name="ingestjob",
            name="error_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Machine-readable reason the ingest failed; empty otherwise. The wording shown to the uploader is the frontend's to choose, not ingest's.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="ingestjob",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ingestjob",
            name="percentage_done",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Progress through the current state, not through the pipeline as a whole. Null where the current state has no progress to report.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ingestjob",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting to be picked up"),
                    ("probing", "Inspecting the uploaded file"),
                    ("archiving", "Storing the original"),
                    ("transcoding", "Generating derived files"),
                    ("done", "Finished"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ingestjob",
            name="status_text",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ingestjob",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="ingest_job",
                serialize=False,
                to="fk.video",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("percentage_done__gte", 0), ("percentage_done__lte", 100)
                ),
                name="ingest_job_percentage_within_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state", "failed"), ("error_code", ""), _connector="OR"
                ),
                name="ingest_job_error_code_only_when_failed",
            ),
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
