# Generated by Django 5.2.17 on 2026-08-18 13:55

from django.db import migrations, models

# MPEG-DASH files are adaptive-streaming manifests: one .mpd per video,
# pointing at the segments beside it. A format with no row is a format
# ingest cannot write, and the two kinds of database get their rows from
# different places: production is migrated and never seeded, so the row
# has to be created here, while a development database is seeded from
# frikanalen.json afterwards -- which rewrites the format table by
# primary key and would otherwise take this row back out. Hence the entry
# there too, and hence get_or_create rather than create.
#
# vod_publish stays false. vod_files() is the old progressive-download
# source list, where every entry is a URL a browser can hand straight to
# a <video> element; a manifest needs a player to interpret it, so it
# does not belong there. The mime type is recorded anyway: it is what the
# manifest is served as, and whoever wires up the player will want it.


def add_dash_format(apps, schema_editor):
    FileFormat = apps.get_model("fk", "FileFormat")
    FileFormat.objects.get_or_create(
        fsname="dash",
        defaults={"mime_type": "application/dash+xml", "vod_publish": False},
    )


def remove_dash_format(apps, schema_editor):
    # Reversing takes 'dash' back out of the permitted names, so any file
    # already registered under it would be left referencing a format that
    # may no longer be created. Deleting the row would fail on the
    # PROTECT anyway; say why instead of surfacing an IntegrityError.
    FileFormat = apps.get_model("fk", "FileFormat")
    VideoFile = apps.get_model("fk", "VideoFile")
    dash = FileFormat.objects.filter(fsname="dash").first()
    if dash is None:
        return
    in_use = VideoFile.objects.filter(format=dash).count()
    if in_use:
        raise RuntimeError(
            f"{in_use} video file(s) are registered as 'dash'. Remove them (and "
            f"the files they point at) before reversing this migration."
        )
    dash.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0023_ingest_job_reports_upload_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileformat",
            name="fsname",
            field=models.CharField(
                choices=[
                    ("large_thumb", "large_thumb"),
                    ("broadcast", "broadcast"),
                    ("vc1", "vc1"),
                    ("med_thumb", "med_thumb"),
                    ("small_thumb", "small_thumb"),
                    ("original", "original"),
                    ("theora", "theora"),
                    ("srt", "srt"),
                    ("cloudflare_id", "cloudflare_id"),
                    ("dash", "dash"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(add_dash_format, reverse_code=remove_dash_format),
    ]
