# Generated by Django 5.2.17 on 2026-08-18 19:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0025_video_file_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="search_document",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    "name", config="norwegian", weight="A"
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="search_document",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "name", config="norwegian", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "header", config="norwegian", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("norwegian"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="norwegian", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("norwegian"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="org_search_document_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="video_search_document_gin"
            ),
        ),
    ]
