# Generated by Django 5.2.17 on 2026-08-21 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0029_scheduleitem_airtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tva_genre",
            field=models.CharField(
                blank=True,
                help_text="Classification scheme term this category is published as in the TV-Anytime feed, as a full href -- for example urn:tva:metadata:cs:ContentCS:2011:3.1.2 for Religion/Philosophies. Leave blank to publish no genre for this category.",
                max_length=255,
                verbose_name="TV-Anytime genre",
            ),
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="is_live",
            field=models.BooleanField(
                default=False,
                help_text="Whether this item goes out live rather than from a file.",
                verbose_name="Live broadcast",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="minimum_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "All ages"),
                    (6, "6"),
                    (9, "9"),
                    (12, "12"),
                    (15, "15"),
                    (18, "18"),
                ],
                help_text="Norwegian age rating (Medietilsynet's scale). Leave blank when the programme has not been rated -- blank publishes no rating at all, while 'All ages' publishes one.",
                null=True,
                verbose_name="Minimum age",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="spoken_language",
            field=models.CharField(
                blank=True,
                default="no",
                help_text="Language tag for the speech in this programme, e.g. 'no', 'nn', 'se' (Northern Sami) or 'en'. Leave blank if there is no speech.",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a language tag such as 'no', 'nn', 'se' or 'en-GB'.",
                        regex="^[a-zA-Z]{2,8}(-[a-zA-Z0-9]{1,8})*$",
                    )
                ],
                verbose_name="Spoken language",
            ),
        ),
    ]
