# Generated by Django 5.2.17 on 2026-08-21 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0031_seed_tva_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="episode_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Episode number within the series. Leave blank when the series is unordered.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("synopsis", models.TextField(blank=True, max_length=2048)),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Public HTTPS URL for series artwork. Leave blank when no artwork is available.",
                        max_length=1024,
                        validators=[django.core.validators.URLValidator(schemes=("https",))],
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization responsible for the series.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="fk.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ("name", "id"),
            },
        ),
        migrations.AddField(
            model_name="video",
            name="series",
            field=models.ForeignKey(
                blank=True,
                help_text="Series this video is an episode of, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="videos",
                to="fk.series",
            ),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("series__isnull", False),
                    ("episode_number__isnull", True),
                    _connector="OR",
                ),
                name="video_episode_number_requires_series",
            ),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                condition=models.Q(("episode_number__isnull", False)),
                fields=("series", "episode_number"),
                name="video_episode_number_unique_per_series",
            ),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="series_name_unique_per_organization",
            ),
        ),
    ]
