# Generated by Django 5.2.17 on 2026-08-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0032_video_episode_number_series_video_series_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("network_logo", "Network logo"),
                            ("channel_logo", "Channel logo"),
                            ("show_logo", "Show logo"),
                            ("show_still", "Show still"),
                            ("episode_still", "Episode still"),
                            ("key_art_titled", "Key art with title"),
                            ("key_art_untitled", "Key art without title"),
                            ("behind_the_scenes", "Behind the scenes"),
                            ("location", "Location"),
                            ("news_event", "News event"),
                            ("portrait_headshot", "Portrait, headshot"),
                            ("portrait_half_body", "Portrait, half body"),
                            ("portrait_full_body", "Portrait, full body"),
                            ("cast_ensemble", "Cast ensemble"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=300, unique=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image/jpeg", "JPEG"),
                            ("image/png", "PNG"),
                            ("image/webp", "WebP"),
                        ],
                        max_length=16,
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="fk.video",
                    ),
                ),
            ],
            options={
                "ordering": ("video_id", "role", "id"),
            },
        ),
    ]
