# Generated by Django 5.2.17 on 2026-08-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Labels only -- help_text, choice labels and verbose names, so that
    the admin says what a SchedulePurpose does. No column changes, and no
    stored value changes: the choice *values* are the ones already in the
    table."""

    dependencies = [
        ("fk", "0033_program_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedulepurpose",
            options={
                "ordering": ("-id",),
                "verbose_name": "weekly slot source",
                "verbose_name_plural": "weekly slot sources",
            },
        ),
        migrations.AlterField(
            model_name="schedulepurpose",
            name="direct_videos",
            field=models.ManyToManyField(
                blank=True,
                help_text="For hand-picked sources: the videos to draw from. Ignored otherwise.",
                to="fk.video",
            ),
        ),
        migrations.AlterField(
            model_name="schedulepurpose",
            name="name",
            field=models.CharField(
                help_text="Shown wherever a slot names its source, including the public planner.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="schedulepurpose",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="For organization sources: whose uploads to draw from. Ignored otherwise.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fk.organization",
            ),
        ),
        migrations.AlterField(
            model_name="schedulepurpose",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("latest", "The newest upload"),
                    ("random", "A random one"),
                    ("least_scheduled", "The one that has aired the least"),
                ],
                help_text="Which candidate airs when a slot using this source comes round.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="schedulepurpose",
            name="type",
            field=models.CharField(
                choices=[
                    ("videos", "Hand-picked videos"),
                    ("organization", "Everything one organization has uploaded"),
                ],
                help_text="Where the candidate videos come from.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="weeklyslot",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                help_text="Which source picks the video for this slot. Blank means the slot reserves airtime that nothing is scheduled into automatically.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fk.schedulepurpose",
                verbose_name="source",
            ),
        ),
    ]
