# Generated by Django 5.2.17 on 2026-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0035_weekly_slot_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="profile_revision",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Revision of the encoding profile that produced this file. 0 means it predates profile tracking.",
            ),
        ),
    ]
