# Generated by Django 5.2.17 on 2026-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0036_videofile_profile_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestjob",
            name="claimed_by",
            field=models.CharField(
                blank=True,
                help_text="Identity of the worker that last claimed this job, if any.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ingestjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("upload", "Source is a fresh upload in the tusd volume"),
                    ("backfill", "Source is the media archive"),
                ],
                db_index=True,
                default="upload",
                help_text="Where this job's source file is, and therefore which workers can take it.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ingestjob",
            name="priority",
            field=models.SmallIntegerField(
                db_index=True,
                default=0,
                help_text="Claim order among waiting jobs; higher is claimed sooner.",
            ),
        ),
    ]
