# Generated by Django 5.2.17 on 2026-08-26 11:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.db.models.functions import Concat


def merge_header_into_description(apps, schema_editor):
    Video = apps.get_model("fk", "Video")
    database = schema_editor.connection.alias

    # Empty strings are absent in the same way as NULL. A whitespace-only
    # value is content, though, and must be preserved rather than stripped.
    videos_with_headers = (
        Video.objects.using(database).filter(header__isnull=False).exclude(header="")
    )
    videos_with_headers.update(
        description=models.Case(
            models.When(
                models.Q(description__isnull=True) | models.Q(description=""),
                then=models.F("header"),
            ),
            default=Concat(
                models.F("header"),
                models.Value("\n\n"),
                models.F("description"),
                output_field=models.TextField(),
            ),
            output_field=models.TextField(),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0037_ingest_job_claiming"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="video_search_document_gin",
        ),
        migrations.RemoveField(
            model_name="video",
            name="search_document",
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(merge_header_into_description, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="video",
            name="header",
        ),
        migrations.AddField(
            model_name="video",
            name="search_document",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "name", config="norwegian", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="norwegian", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("norwegian"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="video_search_document_gin"
            ),
        ),
    ]
