# Generated by Django 5.2.17 on 2026-08-26 23:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def infer_legacy_ownership(apps, schema_editor):
    WeeklySlotSource = apps.get_model("fk", "WeeklySlotSource")
    WeeklySlot = apps.get_model("fk", "WeeklySlot")

    # Hand-picked sources historically ignored `organization`. Recover it
    # when every selected video has one common owner; ambiguous and empty
    # pools remain staff-only.
    for source in WeeklySlotSource.objects.filter(organization__isnull=True):
        organization_ids = list(
            source.direct_videos.order_by()
            .values_list("organization_id", flat=True)
            .distinct()[:2]
        )
        if len(organization_ids) == 1:
            source.organization_id = organization_ids[0]
            source.save(update_fields=("organization",))

    for slot in WeeklySlot.objects.select_related("source").all():
        if slot.source_id and slot.source.organization_id:
            slot.organization_id = slot.source.organization_id
            slot.save(update_fields=("organization",))


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0038_merge_video_header_into_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyslot",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that controls what fills this slot. Legacy unowned slots are staff-only.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fk.organization",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyslotsource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that controls this source. For organization sources, its uploads are also the candidate pool.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fk.organization",
            ),
        ),
        migrations.RunPython(
            infer_legacy_ownership,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="WeeklySlotCreationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("admin_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(0)
                            )
                        ]
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fk.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_slot_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_weekly_slot_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creation_requests",
                        to="fk.weeklyslot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("duration__gte", datetime.timedelta(0))),
                        name="weeklyslotcreationrequest_duration_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_at__isnull", True),
                                ("reviewed_by__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("reviewed_by__isnull", False),
                                ("status__in", ("approved", "denied")),
                            ),
                            _connector="OR",
                        ),
                        name="weeklyslotcreationrequest_decision_audit_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "approved"), ("weekly_slot__isnull", False)
                            ),
                            models.Q(
                                ("status__in", ("pending", "denied")),
                                ("weekly_slot__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="weeklyslotcreationrequest_result_consistent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklySlotOwnershipRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("admin_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fk.organization",
                    ),
                ),
                (
                    "previous_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target slot's owner when the request was submitted.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_slot_transfer_requests",
                        to="fk.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_slot_ownership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_weekly_slot_ownership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership_requests",
                        to="fk.weeklyslot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_at__isnull", True),
                                ("reviewed_by__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("reviewed_by__isnull", False),
                                ("status__in", ("approved", "denied")),
                            ),
                            _connector="OR",
                        ),
                        name="weeklyslotownershiprequest_decision_audit_consistent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("organization", "weekly_slot"),
                        name="one_pending_ownership_request_per_organization_slot",
                    ),
                ],
            },
        ),
    ]
