# Generated by Django 5.2.17 on 2026-09-04 18:51

from django.db import migrations, models

# Adds the `dash_preview` variant: a transient, single-rung DASH ladder
# ingest writes first so an upload becomes playable long before the full
# `dash` ladder is done, and deletes once that ladder is online.
#
# Choices are not enforced by the database, so this touches no data and
# takes no lock worth naming -- it exists so the migration state matches
# the enum, and reverses cleanly as long as no row has been written under
# the new name yet.


class Migration(migrations.Migration):
    dependencies = [
        ("fk", "0039_weekly_slot_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="variant",
            field=models.CharField(
                choices=[
                    ("large_thumb", "Large thumbnail"),
                    ("broadcast", "Broadcast master"),
                    ("vc1", "VC-1"),
                    ("med_thumb", "Medium thumbnail"),
                    ("small_thumb", "Small thumbnail"),
                    ("original", "Original upload"),
                    ("theora", "Ogg Theora"),
                    ("srt", "SubRip subtitles"),
                    ("cloudflare_id", "Cloudflare Stream identifier"),
                    ("dash", "MPEG-DASH manifest"),
                    ("dash_preview", "Transient low-quality MPEG-DASH manifest"),
                    ("webm_med", "Medium-quality WebM"),
                ],
                max_length=20,
            ),
        ),
    ]
